packages:
  - "apps/*"
catalog:
  "@crossmint/client-sdk-react-ui": 2.2.16
  "react": 19.0.0
  "react-dom": 19.0.0
  "@vercel/analytics": 1.5.0
  "clsx": 2.1.1
  "next": 15.2.3
  "tailwind-merge": 3.0.2
  "tw-animate-css": 1.2.4
  "viem": 2.30.6
  "wagmi": 2.15.4
  "@tanstack/react-query": 5.79.0