packages:
  - "apps/*"
catalog:
  "@crossmint/client-sdk-react-ui": 2.3.4
  "react": 19.0.0
  "react-dom": 19.0.0
  "@vercel/analytics": 1.5.0
  "clsx": 2.1.1
  "next": 15.2.4
  "tailwind-merge": 3.0.2
  "tw-animate-css": 1.2.4