packages:
  - "apps/*"
catalog:
  "@crossmint/client-sdk-react-ui": 2.6.9
  "react": 19.0.0
  "react-dom": 19.0.0
  "@vercel/analytics": 1.6.1
  "clsx": 2.1.1
  "next": 16.0.8
  "tailwind-merge": 3.0.2
  "tw-animate-css": 1.2.4
  "viem": 2.40.3
  "wagmi": 3.0.2
  "@tanstack/react-query": 5.90.11